query Cancellations($all: Boolean = true) {
  bookings(all: $all) {
    nodes {
      ... on SingleStudentBooking {
        student {
          firstName
          lastName
        }
        instructor {
          firstName
          lastName
        }
        startsAt
        endsAt
        cancellation {
          comment
          id
          title
          user {
            callSign
          }
        }
        
      }
    }
  }
}